### ISSUE TITLE
New bug fix release on galaxy?

### ISSUE THREAD

**Issue by rezib** [systemli/ansible-role-bind9#57]
Hi @0x46616c6b,

Thank you for this great and helpful bind role. Would you consider publishing a bug fix release on ansible galaxy?

The latest release available there is 1.3.0. I notably hit #42 when using it, this is a pity when the bug is already fixed in the git repo!

**Comment by doobry-systemli** [comment]
Hey @rezib. We just pushed a new tag which hopfully results in a new release on Ansible Galaxy.

**Comment by rezib** [comment]
Well, it seems something didn't work :/ I still can't see 1.4.0 there : https://galaxy.ansible.com/systemli/bind9

**Comment by 0x46616c6b** [comment]
Can you now try it again? I implemented a fix for releasing our roles to Ansible Galaxy

**Comment by rezib** [comment]
Yes, that's fine, thank you so much!
